version: '3'
volumes:
  mysql-data:
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=wp_gdg
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=wp_gdg
  wordpress:
    image: wordpress
    restart: always
    depends_on: 
      - db
    ports: 
      - 8001:80
    volumes:
      - ./wordpress/public_html:/var/www/html
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wp_gdg
      - WORDPRESS_DB_PASSWORD=123456
      - WORDPRESS_DB_NAME=wp_gdg
